spring.application.name=bank-account-api

spring.output.ansi.enabled=ALWAYS
logging.level.org.hibernate.orm.connections.pooling=WARN

spring.datasource.url=jdbc:postgresql://localhost:5432/bank_account
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

app.security.enabled=false

springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/swagger-ui.html